MyCustomError [36m2021/06/01 15:12:55,900[m [34m[DEBUG][m [org.springframework.core.env.PropertySourcesPropertyResolver] [33m[main][m- Found key 'spring.liveBeansView.mbeanDomain' in PropertySource 'systemProperties' with value of type String
 -MyCustomError [36m2021/06/01 15:12:55,911[m [32m[INFO ][m [org.springframework.boot.StartupInfoLogger] [33m[main][m- Started SubwayApplication in 4.372 seconds (JVM running for 6.014)
 -MyCustomError [36m2021/06/01 15:12:55,927[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert not compiled before execution - invoking compile
 -MyCustomError [36m2021/06/01 15:12:55,931[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:55,933[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.TableMetaDataProviderFactory] [33m[main][m- Using GenericTableMetaDataProvider
 -MyCustomError [36m2021/06/01 15:12:55,933[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GetGeneratedKeys is supported
 -MyCustomError [36m2021/06/01 15:12:55,933[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GeneratedKeysColumnNameArray is supported for H2
 -MyCustomError [36m2021/06/01 15:12:55,956[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieving meta-data for TESTDB/PUBLIC/STATION
 -MyCustomError [36m2021/06/01 15:12:56,096[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,098[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'NAME', sqlType=12, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,100[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Compiled insert object: insert string is [INSERT INTO STATION (NAME) VALUES(?)]
 -MyCustomError [36m2021/06/01 15:12:56,100[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert for table [STATION] compiled
 -MyCustomError [36m2021/06/01 15:12:56,108[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@5602e540]
 -MyCustomError [36m2021/06/01 15:12:56,109[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,109[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,109[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,110[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,113[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@4e9ea32f]
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,118[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@79ec57b8]
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@56ba8e8c]
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,120[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@774c5e5c]
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,121[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,133[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert not compiled before execution - invoking compile
 -MyCustomError [36m2021/06/01 15:12:56,133[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,133[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.TableMetaDataProviderFactory] [33m[main][m- Using GenericTableMetaDataProvider
 -MyCustomError [36m2021/06/01 15:12:56,133[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GetGeneratedKeys is supported
 -MyCustomError [36m2021/06/01 15:12:56,133[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GeneratedKeysColumnNameArray is supported for H2
 -MyCustomError [36m2021/06/01 15:12:56,142[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieving meta-data for TESTDB/PUBLIC/LINE
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'NAME', sqlType=12, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'COLOR', sqlType=12, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'EXTRA_FARE', sqlType=4, nullable=true
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Compiled insert object: insert string is [INSERT INTO LINE (NAME, COLOR, EXTRA_FARE) VALUES(?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,153[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert for table [LINE] compiled
 -MyCustomError [36m2021/06/01 15:12:56,154[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO LINE (NAME, COLOR, EXTRA_FARE) VALUES(?, ?, ?) with: [신분당선, #9ca3af, 0]
 -MyCustomError [36m2021/06/01 15:12:56,154[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,154[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,154[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,154[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,163[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert not compiled before execution - invoking compile
 -MyCustomError [36m2021/06/01 15:12:56,163[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,164[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.TableMetaDataProviderFactory] [33m[main][m- Using GenericTableMetaDataProvider
 -MyCustomError [36m2021/06/01 15:12:56,164[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GetGeneratedKeys is supported
 -MyCustomError [36m2021/06/01 15:12:56,164[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GeneratedKeysColumnNameArray is supported for H2
 -MyCustomError [36m2021/06/01 15:12:56,168[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieving meta-data for TESTDB/PUBLIC/SECTION
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'LINE_ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'UP_STATION_ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'DOWN_STATION_ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'DISTANCE', sqlType=4, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Compiled insert object: insert string is [INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert for table [SECTION] compiled
 -MyCustomError [36m2021/06/01 15:12:56,176[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Executing statement INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?) with batch of size: 2
 -MyCustomError [36m2021/06/01 15:12:56,177[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL batch update [INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,177[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement [INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,177[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,178[m [34m[DEBUG][m [org.springframework.jdbc.support.JdbcUtils] [33m[main][m- JDBC driver supports batch updates
 -MyCustomError [36m2021/06/01 15:12:56,180[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO LINE (NAME, COLOR, EXTRA_FARE) VALUES(?, ?, ?) with: [2호선, #f87171, 0]
 -MyCustomError [36m2021/06/01 15:12:56,180[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,180[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,180[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,180[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,181[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Executing statement INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?) with batch of size: 2
 -MyCustomError [36m2021/06/01 15:12:56,181[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL batch update [INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,181[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement [INSERT INTO SECTION (LINE_ID, UP_STATION_ID, DOWN_STATION_ID, DISTANCE) VALUES(?, ?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,181[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,181[m [34m[DEBUG][m [org.springframework.jdbc.support.JdbcUtils] [33m[main][m- JDBC driver supports batch updates
 -MyCustomError [36m2021/06/01 15:12:56,191[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert not compiled before execution - invoking compile
 -MyCustomError [36m2021/06/01 15:12:56,192[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,192[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.TableMetaDataProviderFactory] [33m[main][m- Using GenericTableMetaDataProvider
 -MyCustomError [36m2021/06/01 15:12:56,192[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GetGeneratedKeys is supported
 -MyCustomError [36m2021/06/01 15:12:56,192[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- GeneratedKeysColumnNameArray is supported for H2
 -MyCustomError [36m2021/06/01 15:12:56,194[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieving meta-data for TESTDB/PUBLIC/MEMBER
 -MyCustomError [36m2021/06/01 15:12:56,212[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'ID', sqlType=-5, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,213[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'EMAIL', sqlType=12, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,213[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'PASSWORD', sqlType=12, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,213[m [34m[DEBUG][m [org.springframework.jdbc.core.metadata.GenericTableMetaDataProvider] [33m[main][m- Retrieved meta-data: 'AGE', sqlType=4, nullable=false
 -MyCustomError [36m2021/06/01 15:12:56,213[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Compiled insert object: insert string is [INSERT INTO MEMBER (EMAIL, PASSWORD, AGE) VALUES(?, ?, ?)]
 -MyCustomError [36m2021/06/01 15:12:56,213[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- JdbcInsert for table [MEMBER] compiled
 -MyCustomError [36m2021/06/01 15:12:56,214[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- The following parameters are used for call INSERT INTO MEMBER (EMAIL, PASSWORD, AGE) VALUES(?, ?, ?) with: [org.springframework.jdbc.core.SqlParameterValue@517bdce0, org.springframework.jdbc.core.SqlParameterValue@7c0b0bd9, org.springframework.jdbc.core.SqlParameterValue@6150afc6]
 -MyCustomError [36m2021/06/01 15:12:56,214[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:12:56,214[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[main][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:12:56,215[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceUtils] [33m[main][m- Fetching JDBC Connection from DataSource
 -MyCustomError [36m2021/06/01 15:12:56,215[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[main][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:12:56,215[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,215[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 2, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:12:56,215[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[main][m- Overriding type info with runtime info from SqlParameterValue: column index 3, SQL type 4, type name null
 -MyCustomError [36m2021/06/01 15:12:56,295[m [34m[DEBUG][m [org.springframework.core.env.PropertySourcesPropertyResolver] [33m[RMI TCP Connection(5)-127.0.0.1][m- Found key 'local.server.port' in PropertySource 'server.ports' with value of type Integer
 -MyCustomError [36m2021/06/01 15:13:24,431[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:13:24,436[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:13:54,443[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:13:54,447[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:14:24,453[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:14:24,454[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:14:54,457[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:14:54,459[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:15:24,463[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:15:24,465[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:15:54,468[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:15:54,469[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:15:56,556[m [32m[INFO ][m [org.apache.juli.logging.DirectJDKLog] [33m[http-nio-8080-exec-2][m- Initializing Spring DispatcherServlet 'dispatcherServlet'
 -MyCustomError [36m2021/06/01 15:15:56,557[m [32m[INFO ][m [org.springframework.web.servlet.FrameworkServlet] [33m[http-nio-8080-exec-2][m- Initializing Servlet 'dispatcherServlet'
 -MyCustomError [36m2021/06/01 15:15:56,558[m [34m[DEBUG][m [org.springframework.web.servlet.DispatcherServlet] [33m[http-nio-8080-exec-2][m- Detected StandardServletMultipartResolver
 -MyCustomError [36m2021/06/01 15:15:56,558[m [34m[DEBUG][m [org.springframework.web.servlet.DispatcherServlet] [33m[http-nio-8080-exec-2][m- Detected AcceptHeaderLocaleResolver
 -MyCustomError [36m2021/06/01 15:15:56,558[m [34m[DEBUG][m [org.springframework.web.servlet.DispatcherServlet] [33m[http-nio-8080-exec-2][m- Detected FixedThemeResolver
 -MyCustomError [36m2021/06/01 15:15:56,566[m [34m[DEBUG][m [org.springframework.web.servlet.DispatcherServlet] [33m[http-nio-8080-exec-2][m- Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@3ce14bf8
 -MyCustomError [36m2021/06/01 15:15:56,566[m [34m[DEBUG][m [org.springframework.web.servlet.DispatcherServlet] [33m[http-nio-8080-exec-2][m- Detected org.springframework.web.servlet.support.SessionFlashMapManager@5f276fc3
 -MyCustomError [36m2021/06/01 15:15:56,566[m [34m[DEBUG][m [org.springframework.web.servlet.FrameworkServlet] [33m[http-nio-8080-exec-2][m- enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
 -MyCustomError [36m2021/06/01 15:15:56,566[m [32m[INFO ][m [org.springframework.web.servlet.FrameworkServlet] [33m[http-nio-8080-exec-2][m- Completed initialization in 9 ms
 -MyCustomError [36m2021/06/01 15:15:56,573[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-2][m- POST "/stations", parameters={}
 -MyCustomError [36m2021/06/01 15:15:56,576[m [34m[DEBUG][m [springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping] [33m[http-nio-8080-exec-2][m- looking up handler for path: /stations
 -MyCustomError [36m2021/06/01 15:15:56,581[m [34m[DEBUG][m [org.springframework.web.servlet.handler.AbstractHandlerMapping] [33m[http-nio-8080-exec-2][m- Mapped to wooteco.subway.station.ui.StationController#createStation(StationRequest)
 -MyCustomError [36m2021/06/01 15:15:56,634[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-2][m- Read "application/json;charset=UTF-8" to [wooteco.subway.station.dto.StationRequest@737966]
 -MyCustomError [36m2021/06/01 15:15:56,674[m [30m[TRACE][m [org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree] [33m[http-nio-8080-exec-2][m- Validating value name against constraint defined by ConstraintDescriptorImpl{annotation=j.v.c.NotBlank, payloads=[], hasComposingConstraints=true, isReportAsSingleInvalidConstraint=false, constraintLocationKind=FIELD, definedOn=DEFINED_LOCALLY, groups=[interface javax.validation.groups.Default], attributes={groups=[Ljava.lang.Class;@684a0360, message=역 이름은 빈칸일 수 없습니다., payload=[Ljava.lang.Class;@781e0136}, constraintType=GENERIC, valueUnwrapping=DEFAULT}.
 -MyCustomError [36m2021/06/01 15:15:56,689[m [34m[DEBUG][m [org.springframework.transaction.support.AbstractPlatformTransactionManager] [33m[http-nio-8080-exec-2][m- Creating new transaction with name [wooteco.subway.station.application.StationService.saveStation]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
 -MyCustomError [36m2021/06/01 15:15:56,689[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-2][m- Acquired Connection [HikariProxyConnection@703418249 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] for JDBC transaction
 -MyCustomError [36m2021/06/01 15:15:56,690[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-2][m- Switching JDBC Connection [HikariProxyConnection@703418249 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] to manual commit
 -MyCustomError [36m2021/06/01 15:15:56,697[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing prepared SQL query
 -MyCustomError [36m2021/06/01 15:15:56,698[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing prepared SQL statement [SELECT EXISTS (SELECT id FROM STATION WHERE name = ?)]
 -MyCustomError [36m2021/06/01 15:15:56,705[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[http-nio-8080-exec-2][m- The following parameters are used for call INSERT INTO STATION (NAME) VALUES(?) with: [org.springframework.jdbc.core.SqlParameterValue@2c1652c5]
 -MyCustomError [36m2021/06/01 15:15:56,705[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing SQL update and returning generated keys
 -MyCustomError [36m2021/06/01 15:15:56,705[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing prepared SQL statement
 -MyCustomError [36m2021/06/01 15:15:56,705[m [34m[DEBUG][m [org.springframework.jdbc.core.simple.AbstractJdbcInsert] [33m[http-nio-8080-exec-2][m- Using generated keys support with array of column names.
 -MyCustomError [36m2021/06/01 15:15:56,705[m [34m[DEBUG][m [org.springframework.jdbc.core.StatementCreatorUtils] [33m[http-nio-8080-exec-2][m- Overriding type info with runtime info from SqlParameterValue: column index 1, SQL type 12, type name null
 -MyCustomError [36m2021/06/01 15:15:56,706[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing prepared SQL query
 -MyCustomError [36m2021/06/01 15:15:56,706[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-2][m- Executing prepared SQL statement [SELECT DISTINCT L.id as line_id, L.name as line_name, L.color as line_color, L.extra_fare as extra_fare FROM LINE L left outer join SECTION S WHERE L.id = S.line_id AND (S.up_station_id =? OR S.down_station_id = ?)]
 -MyCustomError [36m2021/06/01 15:15:56,711[m [34m[DEBUG][m [org.springframework.transaction.support.AbstractPlatformTransactionManager] [33m[http-nio-8080-exec-2][m- Initiating transaction commit
 -MyCustomError [36m2021/06/01 15:15:56,711[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-2][m- Committing JDBC transaction on Connection [HikariProxyConnection@703418249 wrapping conn0: url=jdbc:h2:mem:testdb user=SA]
 -MyCustomError [36m2021/06/01 15:15:56,714[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-2][m- Releasing JDBC Connection [HikariProxyConnection@703418249 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] after transaction
 -MyCustomError [36m2021/06/01 15:15:56,728[m [34m[DEBUG][m [org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor] [33m[http-nio-8080-exec-2][m- Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
 -MyCustomError [36m2021/06/01 15:15:56,729[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-2][m- Writing [wooteco.subway.station.dto.StationResponse@5d3013c0]
 -MyCustomError [36m2021/06/01 15:15:56,742[m [34m[DEBUG][m [org.springframework.web.servlet.FrameworkServlet] [33m[http-nio-8080-exec-2][m- Completed 201 CREATED
 -MyCustomError [36m2021/06/01 15:16:00,677[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-3][m- POST "/stations", parameters={}
 -MyCustomError [36m2021/06/01 15:16:00,681[m [34m[DEBUG][m [springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping] [33m[http-nio-8080-exec-3][m- looking up handler for path: /stations
 -MyCustomError [36m2021/06/01 15:16:00,685[m [34m[DEBUG][m [org.springframework.web.servlet.handler.AbstractHandlerMapping] [33m[http-nio-8080-exec-3][m- Mapped to wooteco.subway.station.ui.StationController#createStation(StationRequest)
 -MyCustomError [36m2021/06/01 15:16:00,690[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-3][m- Read "application/json;charset=UTF-8" to [wooteco.subway.station.dto.StationRequest@676455f]
 -MyCustomError [36m2021/06/01 15:16:00,698[m [30m[TRACE][m [org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree] [33m[http-nio-8080-exec-3][m- Validating value name against constraint defined by ConstraintDescriptorImpl{annotation=j.v.c.NotBlank, payloads=[], hasComposingConstraints=true, isReportAsSingleInvalidConstraint=false, constraintLocationKind=FIELD, definedOn=DEFINED_LOCALLY, groups=[interface javax.validation.groups.Default], attributes={groups=[Ljava.lang.Class;@684a0360, message=역 이름은 빈칸일 수 없습니다., payload=[Ljava.lang.Class;@781e0136}, constraintType=GENERIC, valueUnwrapping=DEFAULT}.
 -MyCustomError [36m2021/06/01 15:16:00,702[m [34m[DEBUG][m [org.springframework.transaction.support.AbstractPlatformTransactionManager] [33m[http-nio-8080-exec-3][m- Creating new transaction with name [wooteco.subway.station.application.StationService.saveStation]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
 -MyCustomError [36m2021/06/01 15:16:00,702[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-3][m- Acquired Connection [HikariProxyConnection@145865697 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] for JDBC transaction
 -MyCustomError [36m2021/06/01 15:16:00,703[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-3][m- Switching JDBC Connection [HikariProxyConnection@145865697 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] to manual commit
 -MyCustomError [36m2021/06/01 15:16:00,703[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-3][m- Executing prepared SQL query
 -MyCustomError [36m2021/06/01 15:16:00,703[m [34m[DEBUG][m [org.springframework.jdbc.core.JdbcTemplate] [33m[http-nio-8080-exec-3][m- Executing prepared SQL statement [SELECT EXISTS (SELECT id FROM STATION WHERE name = ?)]
 -MyCustomError [36m2021/06/01 15:16:00,708[m [34m[DEBUG][m [org.springframework.transaction.support.AbstractPlatformTransactionManager] [33m[http-nio-8080-exec-3][m- Initiating transaction rollback
 -MyCustomError [36m2021/06/01 15:16:00,709[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-3][m- Rolling back JDBC transaction on Connection [HikariProxyConnection@145865697 wrapping conn0: url=jdbc:h2:mem:testdb user=SA]
 -MyCustomError [36m2021/06/01 15:16:00,712[m [34m[DEBUG][m [org.springframework.jdbc.datasource.DataSourceTransactionManager] [33m[http-nio-8080-exec-3][m- Releasing JDBC Connection [HikariProxyConnection@145865697 wrapping conn0: url=jdbc:h2:mem:testdb user=SA] after transaction
 -MyCustomError [36m2021/06/01 15:16:00,719[m [34m[DEBUG][m [org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver] [33m[http-nio-8080-exec-3][m- Using @ExceptionHandler wooteco.subway.GlobalControllerAdvice#handleException(RuntimeException)
 -MyCustomError [36m2021/06/01 15:16:00,720[m [31m[ERROR][m [wooteco.subway.GlobalControllerAdvice] [33m[http-nio-8080-exec-3][m- 이미 존재하는 역 이름입니다.
 -MyCustomError [36m2021/06/01 15:16:00,732[m [34m[DEBUG][m [org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor] [33m[http-nio-8080-exec-3][m- Using 'application/json', given [*/*] and supported [application/json, application/*+json, application/json, application/*+json]
 -MyCustomError [36m2021/06/01 15:16:00,733[m [34m[DEBUG][m [org.springframework.core.log.LogFormatUtils] [33m[http-nio-8080-exec-3][m- Writing [wooteco.subway.ExceptionResponse@1e09312d]
 -MyCustomError [36m2021/06/01 15:16:00,742[m [34m[DEBUG][m [org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver] [33m[http-nio-8080-exec-3][m- Resolved [wooteco.subway.station.application.StationException: 이미 존재하는 역 이름입니다.]
 -MyCustomError [36m2021/06/01 15:16:00,742[m [34m[DEBUG][m [org.springframework.web.servlet.FrameworkServlet] [33m[http-nio-8080-exec-3][m- Completed 400 BAD_REQUEST
 -MyCustomError [36m2021/06/01 15:16:24,477[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:16:24,481[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:16:54,487[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:16:54,487[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:17:24,496[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:17:24,499[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:17:54,505[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:17:54,507[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:18:24,513[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:18:24,514[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:18:54,519[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:18:54,519[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:19:24,524[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:19:24,526[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:19:54,530[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:19:54,531[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:20:24,535[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:20:24,539[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:20:54,544[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:20:54,545[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:21:24,550[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:21:24,550[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:21:54,552[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:21:54,553[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:22:24,561[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:22:24,562[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[HikariPool-1 housekeeper][m- HikariPool-1 - Fill pool skipped, pool is at sufficient level.
 -MyCustomError [36m2021/06/01 15:22:28,661[m [34m[DEBUG][m [org.springframework.context.support.AbstractApplicationContext] [33m[SpringContextShutdownHook][m- Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@126be319, started on Tue Jun 01 15:12:52 KST 2021
 -MyCustomError [36m2021/06/01 15:22:28,666[m [34m[DEBUG][m [org.springframework.core.env.PropertySourcesPropertyResolver] [33m[SpringContextShutdownHook][m- Found key 'spring.liveBeansView.mbeanDomain' in PropertySource 'systemProperties' with value of type String
 -MyCustomError [36m2021/06/01 15:22:28,684[m [34m[DEBUG][m [org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup] [33m[SpringContextShutdownHook][m- Stopping beans in phase 2147483647
 -MyCustomError [36m2021/06/01 15:22:28,685[m [34m[DEBUG][m [org.springframework.context.support.DefaultLifecycleProcessor] [33m[SpringContextShutdownHook][m- Bean 'documentationPluginsBootstrapper' completed its stop procedure
 -MyCustomError [36m2021/06/01 15:22:28,690[m [34m[DEBUG][m [org.springframework.context.support.DefaultLifecycleProcessor] [33m[SpringContextShutdownHook][m- Bean 'webServerGracefulShutdown' completed its stop procedure
 -MyCustomError [36m2021/06/01 15:22:28,691[m [34m[DEBUG][m [org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup] [33m[SpringContextShutdownHook][m- Stopping beans in phase 2147483646
 -MyCustomError [36m2021/06/01 15:22:28,735[m [34m[DEBUG][m [org.springframework.context.support.DefaultLifecycleProcessor] [33m[SpringContextShutdownHook][m- Bean 'webServerStartStop' completed its stop procedure
 -MyCustomError [36m2021/06/01 15:22:28,743[m [32m[INFO ][m [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport] [33m[SpringContextShutdownHook][m- Shutting down ExecutorService 'applicationTaskExecutor'
 -MyCustomError [36m2021/06/01 15:22:28,751[m [34m[DEBUG][m [org.springframework.jmx.export.MBeanExporter] [33m[SpringContextShutdownHook][m- Unregistering JMX-exposed beans on shutdown
 -MyCustomError [36m2021/06/01 15:22:28,753[m [34m[DEBUG][m [org.springframework.jmx.support.MBeanRegistrationSupport] [33m[SpringContextShutdownHook][m- Unregistering JMX-exposed beans
 -MyCustomError [36m2021/06/01 15:22:28,756[m [32m[INFO ][m [com.zaxxer.hikari.HikariDataSource] [33m[SpringContextShutdownHook][m- HikariPool-1 - Shutdown initiated...
 -MyCustomError [36m2021/06/01 15:22:28,757[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[SpringContextShutdownHook][m- HikariPool-1 - Before shutdown stats (total=10, active=0, idle=10, waiting=0)
 -MyCustomError [36m2021/06/01 15:22:28,763[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn0: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,765[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn1: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,766[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn2: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,766[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn3: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,766[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn4: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,767[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn5: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,767[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn6: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,767[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn7: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,767[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn8: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,768[m [34m[DEBUG][m [com.zaxxer.hikari.pool.PoolBase] [33m[HikariPool-1 connection closer][m- HikariPool-1 - Closing connection conn9: url=jdbc:h2:mem:testdb user=SA: (connection evicted)
 -MyCustomError [36m2021/06/01 15:22:28,768[m [34m[DEBUG][m [com.zaxxer.hikari.pool.HikariPool] [33m[SpringContextShutdownHook][m- HikariPool-1 - After shutdown stats (total=0, active=0, idle=0, waiting=0)
 -MyCustomError [36m2021/06/01 15:22:28,768[m [32m[INFO ][m [com.zaxxer.hikari.HikariDataSource] [33m[SpringContextShutdownHook][m- HikariPool-1 - Shutdown completed.
 -